screens:
  - name: 'VS0'
    socket: virtual
    size:
      x: 1600
      y: 900
    position-on-wall:
      x: 0
      y: 0

zones:
  - name: 'Zone1'
    provider: 'Folder1'
    buffer: /tmp/billboard/Folder1
    position:
      x: 0
      y: 0
    size:
      x: '{VS0:sx} * .7'
      y: '{VS0:sy}'
    options:
      logo:
        display: True
        image: '/home/theau/Documents/AML affiches rentree/logos/logo_aml.png'
        position:
          x: 0
          y: 0
        size: 0.1
      default_time: 10

  - name: 'Zone2'
    provider: 'Folder2'
    buffer: /tmp/billboard/Folder2
    position:
      x: '{VS0:sx} * .7'
      y: 0
    size:
      x: '{VS0:sx} * 0.3'
      y: '{VS0:sy} / 2'
    options:
      logo:
        display: False
      default_time: 10

  - name: 'Zone3'
    provider: 'Folder3'
    buffer: /tmp/billboard/Folder3
    position:
      x: '{VS0:sx} * .7'
      y: '{Zone2:sy}'
    size:
      x: '{Zone2:sx}'
      y: '{Zone2:sy}'